
-- DAYLIS SECURE AUTH SETUP
-- Run this in Supabase SQL Editor after creating users in Authentication.

create table if not exists public.daylis_profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  student_name text not null unique,
  role text not null default 'student' check (role in ('student', 'admin')),
  created_at timestamptz not null default now()
);

alter table public.daylis_profiles enable row level security;

drop policy if exists "profiles visible to signed users" on public.daylis_profiles;
create policy "profiles visible to signed users"
on public.daylis_profiles for select
to authenticated
using (true);

create table if not exists public.daylis_entries (
  id bigint generated by default as identity primary key,
  user_id uuid references public.daylis_profiles(id) on delete cascade,
  student_name text not null,
  entry_date date not null,
  listened boolean not null default false,
  comment text not null default '',
  extras jsonb not null default '[]'::jsonb,
  updated_at timestamptz not null default now(),
  unique (student_name, entry_date)
);

alter table public.daylis_entries
  add column if not exists user_id uuid references public.daylis_profiles(id) on delete cascade;

alter table public.daylis_entries enable row level security;

grant select, insert, update, delete on public.daylis_entries to authenticated;
grant select on public.daylis_profiles to authenticated;
grant usage, select on sequence public.daylis_entries_id_seq to authenticated;

create or replace function public.is_daylis_admin()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1 from public.daylis_profiles
    where id = auth.uid() and role = 'admin'
  );
$$;

create or replace function public.daylis_set_entry_owner()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  requested_profile public.daylis_profiles;
begin
  select * into requested_profile
  from public.daylis_profiles
  where student_name = new.student_name;

  if requested_profile.id is null then
    raise exception 'Unknown Daylis profile';
  end if;

  if requested_profile.id <> auth.uid() and not public.is_daylis_admin() then
    raise exception 'You can edit only your own profile';
  end if;

  new.user_id := requested_profile.id;
  new.updated_at := now();
  return new;
end;
$$;

drop trigger if exists daylis_assign_owner on public.daylis_entries;
create trigger daylis_assign_owner
before insert or update on public.daylis_entries
for each row execute function public.daylis_set_entry_owner();

drop policy if exists "signed users read entries" on public.daylis_entries;
drop policy if exists "students insert own entries" on public.daylis_entries;
drop policy if exists "students update own entries" on public.daylis_entries;
drop policy if exists "admin delete entries" on public.daylis_entries;
drop policy if exists "daylis public select" on public.daylis_entries;
drop policy if exists "daylis public insert" on public.daylis_entries;
drop policy if exists "daylis public update" on public.daylis_entries;
drop policy if exists "daylis public delete" on public.daylis_entries;

create policy "signed users read entries"
on public.daylis_entries for select
to authenticated
using (true);

create policy "students insert own entries"
on public.daylis_entries for insert
to authenticated
with check (user_id = auth.uid() or public.is_daylis_admin());

create policy "students update own entries"
on public.daylis_entries for update
to authenticated
using (user_id = auth.uid() or public.is_daylis_admin())
with check (user_id = auth.uid() or public.is_daylis_admin());

create policy "admin delete entries"
on public.daylis_entries for delete
to authenticated
using (public.is_daylis_admin());

alter table public.daylis_entries replica identity full;

do $$
begin
  alter publication supabase_realtime add table public.daylis_entries;
exception
  when duplicate_object then null;
end $$;

-- After creating users, replace the UUIDs and run this block:
-- insert into public.daylis_profiles (id, student_name, role) values
-- ('ALLYAZI-USER-UUID', 'Allyazi', 'student'),
-- ('DARIYA-USER-UUID', 'Dariya', 'student'),
-- ('ASSEL-USER-UUID', 'Assel', 'student'),
-- ('ADELA-USER-UUID', 'Adela', 'student'),
-- ('BAYAN-USER-UUID', 'Bayan', 'student'),
-- ('LORA-USER-UUID', 'Lora', 'student'),
-- ('ANASTEISHA-USER-UUID', 'Anasteisha', 'student'),
-- ('ZHANNA-USER-UUID', 'Zhanna', 'student'),
-- ('ADMIN-USER-UUID', 'Admin', 'admin')
-- on conflict (id) do update
-- set student_name = excluded.student_name,
--     role = excluded.role;
